### ISSUE TITLE
Question about regression baseline subtraction for error trials

### ISSUE THREAD

**Issue by cmmrandau** [NeilwBailey/RELAX#10]
Dear Neil W Bailey
I again want to thank you for the RELAX pipeline, also for the latest addition on ERPs, which I'm currently reading. I have a question about the following:

"For the error-related epochs, we baseline corrected data using the traditional baseline subtraction method from 400 to 100 ms (Bailey et al., 2019b)."

Why is that you are not using the regression baseline subtraction method for error trials? I'm analyzing ERP data from the Flanker paradigm (ERN, CRN, etc.) and have until now used the subtraction method in RELAX - are you recommending the traditional method for these ERPs?

BW
Martin

**Comment by cmmrandau** [comment]
I suspect it has to do with the low number of error trials in some subjects, making the regression the analysis perform worse.

**Comment by NeilwBailey** [comment]
Dear Martin

Thank you for getting in touch about this point, and your appreciation of
relax!

You are right on both points. The regression method seems to be less
effective with a small number of trials. However, it's definitely the
preference if possible (and I regret not making that more clear in the
relax manuscripts!).

Unfortunately there doesn't seem to be a cut off minimum number of epochs
for the regression method to be effective. But it may be worth looking into
the work by Clayson on using dependability statistics to determine the
minimum number of epochs for valid estimation of the error processing ERP.

Kind regards,

Neil

**Comment by cmmrandau** [comment]
Dear Neil
Thanks for the prompt reply. As it stands, I use the regression baseline method on data containing both correct and error trials with correct/error as one level factors. Almost all subjects have at least 17 errors (as per Clayson) and all have more than 6. 

As a side note, I'm using single-trial LIMO analysis as the main analysis method. Because of this, I'm also changing RELAX parameters from default to -0.31 muscle slope, don't remove channels due to muscle noise (default 5%) and remove channels with 15% extreme noise (default 5%) and for epoching I use 100 uV threshold (default 60 uV). These values are of course arbitrary and can't really be argued for. Especially the 5% muscle threshold removed many channels for many subjects, especially more noisy patients. The reasoning is that I preserve more neural activity while LIMO handles outlier trials due to noise. In practice, it means I retain more error trials. 

edit: We will of course also supply information in Supplementary Materials about results for default RELAX parameters as well as for the standard EEGLAB clean_rawdata/ICA pipeline. I'm currently testing different values in the RELAX pipeline. The above settings seems to produce the best group effects in LIMO... which is what's called fishing for results. ;) 

BW
Martin
