### ISSUE TITLE
pop_select error 

### ISSUE THREAD

**Issue by yeowkhoon** [NeilwBailey/RELAX#11]
Hi, 
This is the first time that I'm using RELAX. 
I have checked that all the per-requisites are installed 

I am trying RELAX on just one dataset with 4 EEG channels.

When I run "Pre-process", it terminates after the following messages:
===
Sorting the event table.
pop_epoch():1437 epochs selected
Epoching...
pop_epoch():1437 epochs generated
pop_epoch(): checking epochs for data discontinuity
Re-referencing data
Removing 1 channel(s)...
===
... with a pop_select error: 'nochannel' must be numeric 

![image](https://user-images.githubusercontent.com/91247569/237034402-38f1fa52-caa7-4687-a612-17badee4490b.png)

What am I doing wrong?

Thanks.
Yeow

**Comment by NeilwBailey** [comment]
Dear Yeow

Sorry about this, but RELAX is only intended for the cleaning of EEG
datasets that include an EEG electrode montage with a reasonable electrode
coverage across the majority of the scalp. Both the multi-channel Wiener
filtering and the wavelet enhanced ICA steps require channels in a variety
of locations to accurately capture eye movements and muscle activity in
order to clean these from the data.

As such, I don't think RELAX is the appropriate tool to clean your data.
Hopefully you can find another toolbox that will do the trick.

Kind regards,

Neil

**Comment by yeowkhoon** [comment]
Hi, Nick
Thank you for your fast response and suggestion.

Ah... I was so hoping to use it.

Yeow


Yeow


________________________________
