### ISSUE TITLE
find Noisy Channels error

### ISSUE THREAD

**Issue by Yudai-Iwama** [NeilwBailey/RELAX#12]
Hi.　
Thank you for releasing RELAX.
We are trying to use RELAX for noise cancelling.
When we try to process the .set file added the channel information, we get a find Noisy Channels error. See screenshot.

<img width="531" alt="error" src="https://github.com/NeilwBailey/RELAX/assets/130969520/6a9aa618-a584-408c-b3c8-76b5e88c2b7d">

Can you please help us with a solution in this case?

**Comment by NeilwBailey** [comment]
Unfortunately, there seems to have been an update that causes the PREP scripts to be removed from the Matlab path after RELAX has been run. You could try insert some code to add the paths back into Matlab just preceding the error in the script. For example:

PrepPath1=('C:\Analysis_Tools\eeglab2023.0\plugins\PrepPipeline0.55.4\reporting'); % for some reason the most recent eeglab update sometimes removes this from the matlab path after a script has been run. So making sure it's present.        


    PrepPath2=('C:\Analysis_Tools\eeglab2023.0\plugins\PrepPipeline0.55.4\utilities\'); % for some reason the most recent eeglab update sometimes removes this from the matlab path after a script has been run. So making sure it's present.


    addpath(PrepPath1); % for some reason the most recent eeglab update sometimes removes this from the matlab path after a script has been run. So making sure it's present.        


    addpath(PrepPath2); % for some reason the most recent eeglab update sometimes removes this from the matlab path after a script has been run. So making sure it's present.


    noisyOut = findNoisyChannels(EEG);  

I'll try establish a more permanent solution as soon as I can.

Kind regards,

Neil

**Comment by Yudai-Iwama** [comment]
Dear Nick.
Thank you very much for your reply.　I have tried several fixes based on your teachings but have not been able to successfully resolve the issue.

So I thought that there might be a problem with the format of the EEG data we are using.
If possible, please give me a sample of the EEG data you are using for your analysis.

Thanks again.

**Comment by NeilwBailey** [comment]
Unfortunately I'm not able to share our EEG data. However, it is likely to be more helpful if you share some of the problem EEG data with me, which will allow me to trouble shoot directly with the data that might be causing the issue. If I can get the pipeline working with your data, then I'll be able to directly help you with your specific issue.

Kind regards,

Neil

**Comment by NeilwBailey** [comment]
Dear Iwama

Just wanted to check in after you emailed me directly. Unfortunately, I could not replicate the issue you had with my system - your data processed without issue on my computer. As such, I'm wondering if it is an issue with one of the dependencies you have installed. It might be worth updating all the dependencies you have installed and trying to run RELAX again.
