### ISSUE TITLE
Unrecognised field "eyeblinkmask" and "NoiseMaskFullLength"

### ISSUE THREAD

**Issue by EliseJis** [NeilwBailey/RELAX#13]
Hi Neil,
I'm preprocessing 5-minutes resting-state eyes-closed data without MWF. For a while, the code worked fine but now I start getting errors that certain fields are not recognised. When debugging the code, the fields are never created but I can't figure out why. I set RELAX_cfg.ProbabilityDataHasNoBlinks=2; because if when set to 1, I got the following error for one of my participants:

```
Array indices must be positive integers or logical values.

Error in RELAX_blinks_IQR_method (line 127)
                continuousEEG.RELAXProcessing.Details.eyeblinkmask(round(BlinkMaxLatency(1,x)-(400/RELAX_cfg.ms_per_sample)):round(BlinkMaxLatency(1,x)+(400/RELAX_cfg.ms_per_sample)))=1;

Error in RELAX_excluding_channels_and_epoching (line 140)
            [continuousEEG_initialblinkmarking, ~] = RELAX_blinks_IQR_method(continuousEEG, epochedEEG, RELAX_cfg);

Error in RELAX_Wrapper (line 192)
    [continuousEEG, epochedEEG] = RELAX_excluding_channels_and_epoching(continuousEEG, RELAX_cfg); % Epoch data, detect extremely bad data, delete channels if over the set threshold for proportion of data affected by extreme outlier for each electrode

Error in RELAX_SET_PARAMETERS_AND_RUN (line 377)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants, RELAX_issues_to_check, RELAXProcessingExtremeRejectionsAllParticipants] = RELAX_Wrapper (RELAX_cfg);
```

Setting the RELAX_cfg.ProbabilityDataHasNoBlinks=2;, resulted in the following error:

```
Unrecognized field name "eyeblinkmask".

Error in RELAX_Wrapper (line 225)
        Marking_all_artifacts_for_SER_ARR.RELAXProcessing.Details.NoiseMaskFullLength(continuousEEG.RELAX.eyeblinkmask==1)=1;

Error in RELAX_SET_PARAMETERS_AND_RUN (line 377)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants, RELAX_issues_to_check, RELAXProcessingExtremeRejectionsAllParticipants] = RELAX_Wrapper (RELAX_cfg);
```

I've attached the output from the Command Window.

For another participant, I got a similar error but then for the field "NoiseMaskFullLength" and was able to circumvent the error by running this code during debugging:
`continuousEEG.RELAXProcessing.Details.NoiseMaskFullLength = NaN(size(continuousEEG.RELAXProcessing.Details.horizontaleyemask));`

I'm not sure whether that will still result in correctly cleaned data but I reckon the error is caused by a similar issue as with "eyeblinkmask"? Could it be my EEG data or is it likely to be some bug in the code? Thank you!

 
[Bug_RELAX_unrecognisedfield.pdf](https://github.com/NeilwBailey/RELAX/files/12081278/Bug_RELAX_unrecognisedfield.pdf)

**Comment by EliseJis** [comment]
Update: I re-downloaded the RELAX_wrapper script and that seemed to have solved the "Unrecognised field eyeblinkmask" issue. However, I still experience the issue with NoiseMaskFullLength for several files:

Unrecognized field name "NoiseMaskFullLength".

```
Error in RELAX_horizontaleye (line 294)
            for e=1:size(continuousEEG.RELAXProcessing.Details.NoiseMaskFullLength,2)

Error in RELAX_Wrapper (line 219)
        [Marking_artifacts_for_SER_ARR] = RELAX_horizontaleye(continuousEEG, RELAX_cfg);

Error in RELAX_SET_PARAMETERS_AND_RUN (line 377)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants, RELAX_issues_to_check, RELAXProcessingExtremeRejectionsAllParticipants] = RELAX_Wrapper (RELAX_cfg);
```

Relax parameters are mostly set to default.

**Comment by NeilwBailey** [comment]
Hi Elise

Thank you for getting in touch about this issue.

Can I just check first that you are using the most recent version of RELAX
(v1.1.4)? Secondly, do you get the same issue if you use the beta version
of RELAX (applying RELAX_Wrapper_beta)?

Kind regards,

Neil

**Comment by EliseJis** [comment]
Hi Neil,

Yes v1.1.4 and I'm not using the beta version. Thank you

Bet wishes,
Elise

**Comment by NeilwBailey** [comment]
Hi Elise

Unfortunately I'm not able to replicate the error you're receiving when
testing on my data.

One thing I have noticed is that the line where the error occurs is
slightly different to the same line in the code for RELAX v1.1.4, and a
line that almost immediately precedes the "RELAX_horizontaleye" function is
"RELAX_muscle", which provides the
"continuousEEG.RELAXProcessing.Details.NoiseMaskFullLength" variable that
seems to be causing the error you've reported. I'm wondering if you may
have deleted the RELAX_muscle line of code, or made another adaptation to
the code that may result in the
"continuousEEG.RELAXProcessing.Details.NoiseMaskFullLength" variable not
being created? Alternatively, I know you mentioned you're using the default
settings, but perhaps you have set a setting that causes the RELAX_muscle
line of code to not be implemented, so the variable is not being created?
(if you work out what this setting is, please let me know and I will test
it on my data then update RELAX so this issue doesn't occur again).

If you would like to send me an example file of the EEG data that you're
trying to clean when the error occurs, I can try debug RELAX using that
data? However, if you are in a rush to clean your data, one way to avoid
all of these issues would be to set: RELAX_cfg.computecleanedmetrics==0 (and
re-run the cleaning at another point in time once we've solve this in order
to obtain the cleaning metrics).

You could also send me the file that is causing the error in the
"RELAX_blinks_IQR_method" function and I can try solve that issue to
include in a future update of RELAX also?

I've also looked into the blink error when the probability of no blinks in
the data is set to 2 (when you get the error: Unrecognized field name
"eyeblinkmask"). That issue can be solved by adjusting the lines of code at
around 220 in the RELAX_Wrapper function (which I'll fix in an update
shortly):
if isfield(continuousEEG.RELAX,'eyeblinkmask')
Marking_all_artifacts_for_SER_ARR.RELAXProcessing.Details.NoiseMaskFullLength(continuousEEG.RELAX.eyeblinkmask==1)=1;

[Marking_all_artifacts_for_SER_ARR] = RELAX_pad_brief_mask_periods
(Marking_all_artifacts_for_SER_ARR, RELAX_cfg, 'blinks');
end

Kind regards,

Neil
