### ISSUE TITLE
Unrecognised variable 'BlinkIndexMetric'

### ISSUE THREAD

**Issue by varghesepeter17** [NeilwBailey/RELAX#14]
I am using RELAX to clean continuous EEG recorded from 64 channels using the RELAX GUI with default options. I am getting the attached error. Any help in fixing this is appreciated.
MATLAB 2023a
EEGLAB 2023.0
RELAX 1.4
![error](https://github.com/NeilwBailey/RELAX/assets/21120074/5314069f-5949-49a3-bb87-cec6c98c087f)

**Comment by NeilwBailey** [comment]
Hi there

Thank you for letting me know about the error. Can I just check - if you
conduct a visual inspection of the data, are there any blinks in the trace?

I'm about to provide an update that will fix this issue when no blinks are
in the data, but without further information, it's hard to tell if this
will fix the problem you're reporting.

Kind regards,

Neil

**Comment by NeilwBailey** [comment]
RELAX has now been updated to hopefully address this issue. If it still arises, please let me know.

**Comment by IridescentLumos** [comment]
I use the latest RELAX，but I atill have this error
![Uploading 屏幕截图 2024-07-16 142649.png…]()

**Comment by mitanshu7** [comment]
@IridescentLumos, same here!
