### ISSUE TITLE
A problem with"BlinkIndexMetric"

### ISSUE THREAD

**Issue by IridescentLumos** [NeilwBailey/RELAX#19]
Hello,Bailey!
I try to load my dataset into RELAX,but an error occured,as below.
![DE49FE800300D194872C482720265779](https://github.com/user-attachments/assets/db96b1c4-b907-42bf-be58-f116147c0c22)
MATLAB R2024a
EEGLAB 2024
RELAX v2.0.0

**Comment by NeilwBailey** [comment]
Hi there

Unfortunately I won't be able to trouble shoot this error without more information. The easiest way for me to trouble shoot this would be for you to send me the EEG file causing this error. If this isn't possible, it would be helpful to let me know details about the data (recording type, how many electrodes, length of recording, whether there are blinks etc.), and which sub-function was being implemented when the error occurred (RELAX_blinks_IQR_method is called by multiple functions).

Kind regards,

Neil

**Comment by IridescentLumos** [comment]
[RELAX_target_data.zip](https://github.com/user-attachments/files/16262000/RELAX_target_data.zip)
This zip includes both the EEG file I use RELAX to process with,which named target1.set and the RELAX_cfg file.I only tried to run RELAX's"PreProcess EEG Data"  and occured that error.I sincerely hope you can help me overcome this error.Thank U very much.

**Comment by NeilwBailey** [comment]
Hi there

Thank you for sharing the EEG file with me, it makes it much easier to help
troubleshoot.

There are a few compatibility issues with the EEG file you've sent and the
RELAX pre-processing pipeline, which may or may not be able to be overcome:

1) the file that you've sent seems to be segmented into epochs surrounding
task relevant triggers (even though it's formatted in EEGLAB in a
continuous format). RELAX is designed to clean continuous EEG data (data
that is recorded and is formatted without any discontinuities,
segmentation, or epoching). If you have access to the data prior to
segmenting it into task relevant epochs (i.e. the continuous data), then I
would suggest attempting to use RELAX to clean the continuous data from
that stage instead.

2) the file only contains 16 electrodes. RELAX was designed to be applied
to recordings with 32 or more electrodes, so the bad electrode and artifact
rejection steps might not function optimally (they may function OK, but
you'd have to test to make sure), and the ICA decomposition and artifact
component detection with ICLabel also may not function well (ICLabel was
trained on data containing 32 or more electrodes). You could just implement
MWF cleaning to avoid this issue, but I'm not sure how well MWF cleaning
will function with just 16 electrodes either (it might perform well, but I
haven't tested it with 16 electrodes previously, so you'd have to
experiment and visually inspect the cleaned data to confirm).

3) the reason for the error message is likely that the blink artifacts
recorded in your data show negative deflections. Can I ask what EEG system
and reference electrode you use? I'm used to seeing positive voltage
deflections for blink artifacts, and RELAX is coded to detect blinks as a
large positive voltage deflection in frontal electrodes. If you have access
to the continuous data and let me know these details, I might be able to
update RELAX to account for these negative voltage deflection blink
artifacts, so you can get RELAX working on your data (although point 2
might still be an issue).

Kind regards,

Neil

**Comment by IridescentLumos** [comment]
Hi,Bailey!
Thank you very much for pointing me out the issues with my EEG file and RELAX pipeline.
1. I have asked my fellow and only got a small continuous fragment of my current EEG file(converted from txt file),which might be too small to support your update(I am quite sorry about that).Here is the fragment of the continuous EEG:[continuous_target_1.zip](https://github.com/user-attachments/files/16370132/continuous_target_1.zip),it includes the original txt file and the continuous EEG file which is converted from the txt file.
2. I am not sure about the EEG system,probably the 10-20 system.Besides,no electrodes are used as a reference.
3.About the negative deflection blink,I think that absolute values may be a way to convert the blink of a negative voltage deflection to a positive voltage deflection.
At last,I want to thank you for your reply again!

**Comment by NeilwBailey** [comment]
Hi there

Unfortunately that file is too short for me to be able to conduct any troubleshooting using it. Given that there are several potential incompatibilities between your data and the implementation of RELAX, I'd suggest an alternative cleaning method might be worth exploring. 

Kind regards,

Neil
