### ISSUE TITLE
RELAX_wrapper_beta not called

### ISSUE THREAD

**Issue by cmmrandau** [NeilwBailey/RELAX#3]
Dear Neil

Thanks for this update which now provides zapline! :D 

I've found an error: RELAX_SET_PARAMETERS_AND_RUN_beta does not call RELAX_Wrapper_beta at the end so any new calls are not run. It calls the old RELAX_Wrapper. 

Best wishes
Martin

**Comment by NeilwBailey** [comment]
Dear Martin

Thanks for spotting this! I have now updated the code to fix.

Kind regards,

Neil
