### ISSUE TITLE
Issue with opening RELAX parameter setting on eeglab

### ISSUE THREAD

**Issue by Grace85626** [NeilwBailey/RELAX#5]
Hello Neil Bailey,

I'm getting this error when I try to open the RELAX parameter setting in EEGLAB. Kindly see the error message below:

EEGLAB Error in function pop_RELAX () at line 480
"Index exceeds array bounds"

**Comment by NeilwBailey** [comment]
Hi there

Sorry to hear RELAX is not working for you at the moment. I have a few questions to see if we can work out what's going on:

1) Is this error coming up immediately after you click "RELAX > Preprocess EEG data", or is it occurring after you choose the parameters in the window that comes up after that?

2) Have you updated to the v1.1.0 version?

Unfortunately I can't replicate the error at this stage, so hopefully the further information you can provide will help.

Kind regards,

Neil

**Comment by Grace85626** [comment]
Thank you for your response. 
The error comes up after clicking on "RELAX > Preprocess EEG data", but I have been able to resolve the problem. I updated my EEGLAB from the 2019 version to the 2022 version, and it worked.
