### ISSUE TITLE
Biosemi reference

### ISSUE THREAD

**Issue by cmmrandau** [NeilwBailey/RELAX#6]
Hello again Neil W Bailey

I have another issue/question. I have EEG data recorded with Biosemi 64-channels. This system does not use a reference electrode but CMS/DRL. It is recommended to select a reference upon import in EEGLAB in order to cancel common noise. I have R/L mastoid electrodes for this purpose. However, since RELAX applies robust re-referencing in PREP and after re-references to average, won't you agree that I can avoid importing the raw data with average mastoid reference? RELAX fails for some especially noisy datasets when using average mastoid before RELAX, while it works successfully when imported without reference. I suspect line noise in the mastoids is smeared upon the other channels, since zapline keeps on going forever at almost every frequency, and then RELAX fails with: 

```
Unrecognized field name "NumberOfMuscleContaminatedChannelsRecomendedToDelete".

Error in RELAX_excluding_channels_and_epoching (line 438)
    epochedEEG.RELAXProcessingExtremeRejections.NumberOfMuscleContaminatedChannelsRecomendedToDelete=epochedEEG.RELAXProcessing.Details.NumberOfMuscleContaminatedChannelsRecomendedToDelete;

Error in RELAX_Wrapper_beta (line 193)
    [continuousEEG, epochedEEG] = RELAX_excluding_channels_and_epoching(continuousEEG, RELAX_cfg); % Epoch data, detect extremely bad data, delete channels if over the set threshold for proportion of data affected by extreme outlier for each electrode

Error in RELAX_SET_PARAMETERS_AND_RUN_beta (line 376)
        RELAXProcessing_ICA_AllParticipants, RELAXProcessingRoundThreeAllParticipants, RELAX_issues_to_check, RELAXProcessingExtremeRejectionsAllParticipants] = RELAX_Wrapper_beta (RELAX_cfg);
```

BW
Martin

**Comment by NeilwBailey** [comment]
Hi Martin

Yes I think it would be fine to import the data as is without
re-referencing. The MWF cleaning does not require any specific reference
format (and seems to work better with just the online reference used). The
data is re-referenced to the robust average reference (as per PREP) just
before the ICA decomposition is computed (as both ICA and ICLabel seem to
work better with robust average re-referencing).

Kind regards,

Neil
